// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/features/blog/data/local/article_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6177356929457975049),
    name: 'ArticleEntity',
    lastPropertyId: const obx_int.IdUid(12, 9220521203805174285),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8054026832853137321),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2089430366455036154),
        name: 'author',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7415943699945723268),
        name: 'title',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 7522932536883243548),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2258688279939994440),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8820561906452653421),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7343345981176798120),
        name: 'urlToImage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3226775935008999573),
        name: 'publishedAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 635004619506358691),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5483076642094186828),
        name: 'source',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6362227417809720720),
        name: 'isFav',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 9220521203805174285),
        name: 'isWatched',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 273740008228373071),
    lastIndexId: const obx_int.IdUid(2, 7522932536883243548),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [273740008228373071],
    retiredIndexUids: const [4052274468232260939],
    retiredPropertyUids: const [
      3593680680649626775,
      8848491596338528772,
      5765684945153155568,
      5295763711705031737,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ArticleEntity: obx_int.EntityDefinition<ArticleEntity>(
      model: _entities[0],
      toOneRelations: (ArticleEntity object) => [],
      toManyRelations: (ArticleEntity object) => {},
      getId: (ArticleEntity object) => object.id,
      setId: (ArticleEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ArticleEntity object, fb.Builder fbb) {
        final authorOffset = object.author == null
            ? null
            : fbb.writeString(object.author!);
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = fbb.writeString(object.description);
        final urlOffset = fbb.writeString(object.url);
        final urlToImageOffset = fbb.writeString(object.urlToImage);
        final publishedAtOffset = fbb.writeString(object.publishedAt);
        final contentOffset = fbb.writeString(object.content);
        final sourceOffset = fbb.writeString(object.source);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, authorOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, urlOffset);
        fbb.addOffset(5, urlToImageOffset);
        fbb.addOffset(6, publishedAtOffset);
        fbb.addOffset(7, contentOffset);
        fbb.addOffset(9, sourceOffset);
        fbb.addBool(10, object.isFav);
        fbb.addBool(11, object.isWatched);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final sourceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final authorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final urlToImageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final publishedAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final isFavParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final isWatchedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final object = ArticleEntity(
          id: idParam,
          source: sourceParam,
          author: authorParam,
          title: titleParam,
          description: descriptionParam,
          url: urlParam,
          urlToImage: urlToImageParam,
          publishedAt: publishedAtParam,
          content: contentParam,
          isFav: isFavParam,
          isWatched: isWatchedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ArticleEntity] entity fields to define ObjectBox queries.
class ArticleEntity_ {
  /// See [ArticleEntity.id].
  static final id = obx.QueryIntegerProperty<ArticleEntity>(
    _entities[0].properties[0],
  );

  /// See [ArticleEntity.author].
  static final author = obx.QueryStringProperty<ArticleEntity>(
    _entities[0].properties[1],
  );

  /// See [ArticleEntity.title].
  static final title = obx.QueryStringProperty<ArticleEntity>(
    _entities[0].properties[2],
  );

  /// See [ArticleEntity.description].
  static final description = obx.QueryStringProperty<ArticleEntity>(
    _entities[0].properties[3],
  );

  /// See [ArticleEntity.url].
  static final url = obx.QueryStringProperty<ArticleEntity>(
    _entities[0].properties[4],
  );

  /// See [ArticleEntity.urlToImage].
  static final urlToImage = obx.QueryStringProperty<ArticleEntity>(
    _entities[0].properties[5],
  );

  /// See [ArticleEntity.publishedAt].
  static final publishedAt = obx.QueryStringProperty<ArticleEntity>(
    _entities[0].properties[6],
  );

  /// See [ArticleEntity.content].
  static final content = obx.QueryStringProperty<ArticleEntity>(
    _entities[0].properties[7],
  );

  /// See [ArticleEntity.source].
  static final source = obx.QueryStringProperty<ArticleEntity>(
    _entities[0].properties[8],
  );

  /// See [ArticleEntity.isFav].
  static final isFav = obx.QueryBooleanProperty<ArticleEntity>(
    _entities[0].properties[9],
  );

  /// See [ArticleEntity.isWatched].
  static final isWatched = obx.QueryBooleanProperty<ArticleEntity>(
    _entities[0].properties[10],
  );
}
